# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Interactive Audio Lab
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  # ial description
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://music.cs.northwestern.edu/index.php" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  interactiveaudiolab

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: assets/css

# tells jekyll to recognize the listed folders as colections.
# output:true generates individual pages for each item in the collection.
collections:
  datasets:
    output: true
  demos:
    output: true
  members:
    output: true
  projects:
    output: true
  sourcecode:
    output: true
#tells jekyll the directory where all collections are located
collections_dir: collections

#defines what layout each type of collection displays as, as well as its path display.
#the file name of the individual item determines the name of the html path
#note that papers is not listed here because its individual pages aren't linked
defaults:
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "detail"
      permalink: /resources/datasets/:name.html
  - scope:
      path: ""
      type: "demos"
    values:
      layout: "detail"
      permalink: /research/demos/:name.html
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "detail"
      permalink: /research/projects/:name.html
  - scope:
      path: ""
      type: "sourcecode"
    values:
      layout: "detail"
      permalink: /resources/sourcecode/:name.html
  - scope:
      path: ""
    values:
      layout: "default"

# jekyll-scholar settings
scholar:
  style: assets\bibliography\ieee-with-url.csl
  locale: en

  sort_by: year
  order: descending
  bibliography_list_tag: ul

  source: _data
  # repository: http://music.cs.northwestern.edu/publications/
  bibliography: references.bib
  bibliography_template: publications-list

  replace_strings: true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
