# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Interactive Audio Lab
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Lab description
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://music.cs.northwestern.edu/index.php" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github-url:  "https://github.com/interactiveaudiolab"
youtube-url: "https://www.youtube.com/channel/UCY-jggB_-R3rYaTsWN2_Ssw"

# For a bibtex entry in ./data/references.bib to appear in the publications list,  
# its year of publication must be in the list below.
publication-years: [2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000,1998]

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: assets/css

# tells jekyll to recognize the listed folders as colections.
# output:true generates individual pages for each item in the collection.
collections:
  courses:
    output: true
  datasets:
    output: true
  people-current:
    output: true
  people-collaborators:
    output: true
  people-alumni:
    output: true
  projects-search:
    output: true
  projects-separation:
    output: true
  projects-interfaces:
    output: true
  projects-featured:
    output: true
#tells jekyll the directory where all collections are located
collections_dir: collections

#defines what layout each type of collection displays as, as well as its path display.
#the file name of the individual item determines the name of the html path
#note that papers is not listed here because its individual pages aren't linked
defaults:
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "detail"
      permalink: /resources/teaching/:name.html
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "detail"
      permalink: /resources/datasets/:name.html
  - scope:
      path: ""
      type: "people-alumni"
    values:
      layout: "person"
  - scope:
      path: ""
      type: "people-current"
    values:
      layout: "person"
  - scope:
      path: ""
      type: "people-collaborators"
    values:
      layout: "person"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects-search"
    values:
      layout: "detail"
      permalink: /project/:name.html
  - scope:
      path: ""
      type: "projects-separation"
    values:
      layout: "detail"
      permalink: /project/:name.html
  - scope:
      path: ""
      type: "projects-interfaces"
    values:
      layout: "detail"
      permalink: /project/:name.html
  - scope:
      path: ""
      type: "projects-featured"
    values:
      layout: "detail"
      permalink: /project/:name.html
  - scope:
      path: ""
    values:
      layout: "default"


# jekyll-scholar settings
scholar:
  style: assets/bibliography/ieee-with-url.csl
  locale: en

  sort_by: year
  order: descending
  # group_by: year
  # group_order: descending
  bibliography_list_tag: ul

  source: _data
  bibliography: references.bib
  bibliography_template: publications-list

  replace_strings: true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
